### ISSUE TITLE
What counts as a "matching config module"?

### ISSUE THREAD

**Issue by pianocomposer321** [nvim-neorocks/rocks-config.nvim#13]
The README says:

> Upon startup, for each plugin in the rocks.toml's [plugins] table, this module will search for a matching config module in and load it if one is found.

But it doesn't say anywhere what config will match a certain plugin. The example also doesn't give much information. What would I have to name a config file for it to be "matched" by the config loader?

**Comment by mrcjkb** [comment]
Hey :wave: 

I've opened [a PR](https://github.com/nvim-neorocks/rocks-config.nvim/pull/14/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R74) that includes some clearer documentation.

Please feel free to provide feedback if it is still not clear enough :smile:

**Comment by pianocomposer321** [comment]
This answers my question. Thanks for the quick response! 🙌
