### ISSUE TITLE
Cannot find colorscheme error when setting colorscheme in plugin config

### ISSUE THREAD

**Issue by AzurIce** [nvim-neorocks/rocks-config.nvim#22]
I'm trying to install and configure [material.nvim](https://github.com/marko-cerovac/material.nvim)

my `lua/plugin/material.lua` is as follows:

```lua
require('material').setup({
  -- ...
})

vim.cmd.colorscheme 'material'
```

error:

```
5113: Error while calling lua chunk: ...cal/share/nvim/rocks/rocks_rtp/lua/rocks-config/init.lua:41: /Users/azurice/.config
/nvim/lua/plugins/material.lua:69: Vim:E185: cannot find colorscheme 'material'
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/rocks/rocks_rtp/lua/rocks-config/init.lua:41: in function 'setup'
        ...rocks/rocks_rtp/lua/rocks-config/rocks/hooks/preload.lua:20: in function 'hook'
        ...local/share/nvim/rocks/rocks_rtp/lua/rocks/api/hooks.lua:63: in function 'run_preload_hooks'
        .../luarocks/rocks-5.1/rocks.nvim/2.19.1-1/plugin/rocks.lua:31: in main chunk
```

And it doesn't appear in the auto completion of `:colorscheme`,
But if I remove the line `vim.cmd.colorscheme 'material'`, It shows in the colorscheme list, and I can use `:colorscheme` to set it correctly.

What's the proper way to set colorscheme?

**Comment by mrcjkb** [comment]
Hey 👋 

See [this response](https://github.com/nvim-neorocks/rocks.nvim/discussions/212#discussioncomment-8856253) regarding colorschemes 😃

I think we probably need to add some clearer documentation for colorschemes to the readmes. This is the third time this issue has come up :sweat_smile:

**Comment by AzurIce** [comment]
Oh, I see! Thanks very much for your reply, and sorry for bothering again. 🤣

**Comment by mrcjkb** [comment]
This is a rocks.nvim issue, so I've created https://github.com/nvim-neorocks/rocks.nvim/issues/237.
Closing this as duplicate.
