### ISSUE TITLE
[Feature] Option to disable auto_setup on plugin

### ISSUE THREAD

**Issue by bottd** [nvim-neorocks/rocks-config.nvim#40]
To provide more user control while auto_setup enabled it would be nice if you could disable setup on a per-plugin basis.

Example:
```
[plugins.neorg]
version = "7.0.0"
# disables auto_setup
setup = false
```

**Comment by mrcjkb** [comment]
Duplicate of https://github.com/nvim-neorocks/rocks-config.nvim/issues/9 :smile:
