### ISSUE TITLE
[Feature] Api for manually loading bundles

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks-config.nvim#59]
See https://github.com/nvim-neorocks/rocks-lazy.nvim/issues/8.

We could automatically skip loading a bundle if all of its plugins are `opt` (technically a breaking change).

**Comment by teto** [comment]
is it of any interest to map bundles to a single packpath ?

**Comment by mrcjkb** [comment]
> is it of any interest to map bundles to a single packpath ?

I don't understand this.
